-- ==========================================
-- Скрипт: ReplicatedStorage.SharedModules.ContentPacks.Summer2026.Game.Skydiving.SkydivingConstants
-- ==========================================

-- https://lua.expert/
return {
	CYCLE_DURATION = 600,
	MODE_SPEEDS = {
		freefall = {
			fall_speed = 10,
			xz_speed = 25
		},
		pencil_dive = {
			fall_speed = 28,
			xz_speed = 20
		},
		parachute = {
			fall_speed = 3,
			xz_speed = 5
		}
	},
	PARACHUTE_TURN_RATE = math.rad(120),
	PARACHUTE_FORWARD_MULTIPLIER = 1,
	PARACHUTE_PITCH_MIN = 0.3,
	PARACHUTE_PITCH_MAX = 2.5,
	PARACHUTE_ROLL_ANGLE = 0.3490658503988659,
	PARACHUTE_PITCH_ANGLE = 0.6108652381980153,
	PARACHUTE_TILT_SMOOTHING = 8,
	PARACHUTE_LIFT_SPEED = 12,
	PARACHUTE_LIFT_DRAIN_RATE = 0.3,
	PARACHUTE_LIFT_NEUTRAL_RECHARGE_RATE = 0.15,
	PARACHUTE_LIFT_FORWARD_RECHARGE_RATE = 0.25,
	CHARACTER_SPRING_FREQUENCY = 8,
	CHARACTER_SPRING_DAMPING = 1,
	CAMERA_DIVE_INTRO_TIME = 2,
	CAMERA_DIVE_HEIGHT_OFFSET = 15,
	CAMERA_DIVE_BACK_OFFSET = 20,
	CAMERA_DIVE_PITCH = 0.6108652381980153,
	CAMERA_DIVE_SPRING_FREQUENCY = 1.5,
	CAMERA_DIVE_SPRING_DAMPING = 1,
	CAMERA_PENCIL_DIVE_EXTRA_HEIGHT = 8,
	CAMERA_PENCIL_DIVE_EXTRA_BACK = -15,
	CAMERA_PENCIL_DIVE_PITCH_REDUCTION = 0.6,
	CAMERA_PARACHUTE_TRANSITION_TIME = 1,
	CAMERA_PARACHUTE_BEHIND_DISTANCE = 15,
	CAMERA_PARACHUTE_HEIGHT_OFFSET = 20,
	CAMERA_LANDING_TRANSITION_TIME = 0.5,
	DIVE_STEER_RATE = 0.8726646259971648,
	DIVE_STEER_ACCEL = 1.3962634015954636,
	DIVE_STRAFE_FRACTION = 1,
	DIVE_FORWARD_DRIFT = 1.5,
	DIVE_XZ_SMOOTHING = 3,
	DIVE_ROLL_ANGLE = 0.4363323129985824,
	DIVE_PITCH_ANGLE = 0.2617993877991494,
	DIVE_TILT_SMOOTHING = 8,
	PENCIL_DIVE_EXTRA_PITCH = 1.3962634015954636,
	PENCIL_DIVE_TRANSITION_SPEED = 10,
	PARACHUTE_ALTITUDE_THRESHOLD = 50,
	PARACHUTE_TRANSITION_TIME = 1,
	PARACHUTE_LOCAL_TRANSPARENCY_MODIFIER = 0.5,
	RING_PREVIEW_WINDOW = 5,
	RING_BASE_TRANSPARENCY = 0.6,
	TOTAL_RING_CURRENCY = 2000,
	CURRENCY_PILE_AMOUNT_FOR_MAX_STAGE = 3000,
	TARGET_MAX_REWARD = 1000,
	TARGET_OUTER_RADIUS = 250,
	TARGET_BULLSEYE_RADIUS_FRACTION = 0.25,
	VALIDATION_PROXIMITY_RADIUS = 20,
	VALIDATION_MIN_TIME_BETWEEN_RINGS = 0.05,
	VALIDATION_LANDING_TOLERANCE = 15,
	LAUNCH_VERTICAL_IMPULSE = 0.3,
	LAUNCH_FORWARD_IMPULSE = 2,
	LAUNCH_DEPTH_FORWARD_BOOST = 0.1,
	TIME_TRIAL_ABORT_DELAY = 3,
	TIME_TRIAL_LEADERBOARD_SIZE = 16,
	EXIT_TELEPORT_FADE_LENGTH = 0.5,
	EXIT_TELEPORT_HOLD_DURATION = 0.5,
	ACORN_REMINDER_SUPPRESS_ZONE_NAME = "AcornReminderSuppressZone",
	START_SOURCE = {
		CYCLE = 1,
		ADMIN_ABUSE = 2
	}
}

